---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JuerGenie.
--- DateTime: 2019/4/9 23:26
---

function get()
    local tb = {}
    tb['say'] = 'hello world!'
    tb['do'] = 'redirect?'
    return tb, 'testing', 201
end
